# Spring properties
spring:
  application:
     name: service-with-actuator

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# HTTP Server
server:
  port: 9000   # HTTP (Tomcat) port      